"""Immutable Repository Context contracts."""

from .canonical import (
    canonical_bytes,
    contract_id_for,
    error_id_for,
    evidence_id_for,
    sha256_hex,
)
from .models import (
    BoundedOptionalInput,
    CandidateCounts,
    ContentHash,
    EvidenceRef,
    InputSummary,
    Limitation,
    NormalizedInput,
    RankingInputs,
    RelevantFile,
    ResultSetTruncatedDetail,
    RepositoryContextEnvelope,
    RepositoryContextRequest,
    RepositoryContextResult,
    RepositoryContextValidationError,
    ReturnedCounts,
    RunCounts,
    RunSummary,
    SearchResult,
    TestCommandHint,
    TextLocator,
    ValidationErrorSummary,
    WorkspaceRef,
)
from .profile import M1_DEFAULTS, RepositoryContextProfile
from .workspace import WorkspaceBoundary, WorkspaceBoundaryError

__all__ = (
    "BoundedOptionalInput",
    "CandidateCounts",
    "ContentHash",
    "EvidenceRef",
    "InputSummary",
    "Limitation",
    "M1_DEFAULTS",
    "NormalizedInput",
    "RankingInputs",
    "RelevantFile",
    "ResultSetTruncatedDetail",
    "RepositoryContextEnvelope",
    "RepositoryContextProfile",
    "RepositoryContextRequest",
    "RepositoryContextResult",
    "RepositoryContextValidationError",
    "ReturnedCounts",
    "RunCounts",
    "RunSummary",
    "SearchResult",
    "TestCommandHint",
    "TextLocator",
    "ValidationErrorSummary",
    "WorkspaceRef",
    "WorkspaceBoundary",
    "WorkspaceBoundaryError",
    "canonical_bytes",
    "contract_id_for",
    "error_id_for",
    "evidence_id_for",
    "sha256_hex",
)
